# Generated by Django 4.0.3 on 2022-06-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='LisFruits',
            new_name='ListFruits',
        ),
    ]
